Fix order of intrinsic upload region usage in docs
The user documentation stated that the region should be added after the
style of the returned S3 object location.

This causes the look-up of the bucket to use to fail, as it tries to
lookup the bucket for the region referencing the style of the upload.

When using: 'upload:s3-key-only:us-east-1:somefile.zip' you get:

```
errors.ParameterNotFoundError: Parameter /cross_region/s3_regional_bucket/s3-key-only Not Found
```

When looking at the [code](https://github.com/awslabs/aws-deployment-framework/blob/8ae0f35da64e90da3790935a664908e3e5adf133/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver.py#L103)
it shows that the region should be placed before the style.